# Generated by Django 5.1.2 on 2024-10-10 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="document",
        ),
        migrations.AddField(
            model_name="customer",
            name="address_complement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="cnpj",
            field=models.CharField(
                blank=True, max_length=18, null=True, unique=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="rg",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="RG"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Celular",
            ),
        ),
    ]
