# Generated by Django 5.1.2 on 2024-10-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "budget",
            "0002_remove_customer_document_customer_address_complement_and_more",
        ),
    ]

    operations = []
