# Generated by Django 5.1.2 on 2024-10-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_auto_20241010_1853"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                ("nick_name", models.CharField(max_length=100, verbose_name="Apelido")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiais",
                "ordering": ["full_name"],
            },
        ),
    ]
