# Generated by Django 5.1.2 on 2024-10-10 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="cost_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor de Custo",
            ),
        ),
    ]
