# Generated by Django 5.1.2 on 2024-10-10 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_material_cost_value_budget_budgetitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
