# Generated by Django 5.1.2 on 2024-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_remove_budget_updated_at_alter_budgetitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
