# Generated by Django 5.1.2 on 2024-10-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0008_budget_enabled_budgetitem_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cnpj",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="rg",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.IntegerField(
                choices=[(1, "Física"), (2, "Jurídica")],
                default=1,
                verbose_name="Tipo de Cliente",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="document",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Documento",
            ),
        ),
    ]
