# Generated by Django 5.1.2 on 2024-10-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_remove_customer_cnpj_remove_customer_cpf_and_more"),
    ]

    operations = []
