# Generated by Django 5.1.2 on 2024-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_populate_document_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="enabled",
        ),
        migrations.AddField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criado"),
                    ("PENDING", "Pendente Envio"),
                    ("ACCEPTED", "Aceito"),
                    ("CANCELED", "Cancelado"),
                    ("SERVICE_ORDER", "Ordem Serviço"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
