# Generated by Django 5.1.2 on 2024-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0013_customer_enabled_alter_customer_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
