# Generated by Django 5.1.2 on 2024-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0014_budget_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="E-mail"
            ),
        ),
    ]
