# Generated by Django 5.1.2 on 2024-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0015_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Endereço"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address_complement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
