# Generated by Django 5.1.2 on 2024-10-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0020_budgetitem_installation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criado"),
                    ("CANCELED", "Cancelado"),
                    ("PENDING", "Pendente Envio"),
                    ("SENT", "Enviado"),
                    ("ACCEPTED", "Aceito"),
                    ("SERVICE_ORDER", "Ordem de Serviço"),
                    ("SCHEDULED", "Agendado"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
