# Generated by Django 5.1.2 on 2024-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0021_alter_budget_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="installation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
