# Generated by Django 5.1.2 on 2024-10-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0022_budget_installation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("tax", "Imposto"), ("fee", "Taxa")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("acronym", models.CharField(max_length=10, verbose_name="Sigla")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "Estadual"),
                            ("municipal", "Municipal"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "calc_operator",
                    models.CharField(
                        choices=[
                            ("+", "Adição"),
                            ("-", "Subtração"),
                            ("*", "Multiplicação"),
                            ("/", "Divisão"),
                        ],
                        max_length=1,
                        verbose_name="Operador",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Taxa/Imposto",
                "verbose_name_plural": "Taxas e Impostos",
            },
        ),
    ]
