# Generated by Django 5.1.2 on 2024-10-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0023_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tax",
            name="calc_operator",
        ),
        migrations.AddField(
            model_name="tax",
            name="operator",
            field=models.CharField(
                choices=[("percentage", "Percentual"), ("fixed", "Fixo")],
                default="percentage",
                max_length=10,
                verbose_name="Operador",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nseq_apply",
                    models.IntegerField(verbose_name="Sequência de Aplicação"),
                ),
                (
                    "sign",
                    models.CharField(
                        choices=[("+", "Positivo"), ("-", "Negativo")],
                        max_length=1,
                        verbose_name="Sinal",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Habilitado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_entries",
                        to="budget.material",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budget.tax"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Preço",
                "verbose_name_plural": "Listas de Preço",
                "ordering": ["material", "nseq_apply"],
            },
        ),
        migrations.AddField(
            model_name="material",
            name="taxes",
            field=models.ManyToManyField(
                related_name="materials", through="budget.PriceList", to="budget.tax"
            ),
        ),
    ]
