# Generated by Django 5.1.2 on 2024-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0024_remove_tax_calc_operator_tax_operator_pricelist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="taxes",
        ),
        migrations.RemoveField(
            model_name="tax",
            name="operator",
        ),
        migrations.AddField(
            model_name="tax",
            name="calc_operator",
            field=models.CharField(
                choices=[
                    ("+", "Addition"),
                    ("-", "Subtraction"),
                    ("*", "Multiplication"),
                    ("/", "Division"),
                ],
                default="+",
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="PriceList",
        ),
    ]
