# Generated by Django 5.1.2 on 2024-10-17 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0025_remove_material_taxes_remove_tax_operator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="calc_operator",
            field=models.CharField(
                choices=[
                    ("%", "Percentual"),
                    ("0", "Fixo"),
                    ("+", "Adição"),
                    ("-", "Subtração"),
                    ("*", "Multiplicação"),
                    ("/", "Divisão"),
                ],
                default="%",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Price_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "type_tax",
                    models.CharField(
                        choices=[("+", "Positive"), ("-", "Negative")],
                        default="+",
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.material",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget.tax",
                    ),
                ),
            ],
        ),
    ]
