# Generated by Django 5.1.2 on 2024-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0026_alter_tax_calc_operator_price_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="price_list",
            name="tax_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="price_list",
            name="value_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
