# Generated by Django 5.1.2 on 2024-10-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0027_price_list_tax_value_price_list_value_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="cost_value",
        ),
        migrations.AddField(
            model_name="material",
            name="ean_code",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Código EAN"
            ),
        ),
    ]
