# Generated by Django 5.1.2 on 2024-10-17 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0028_remove_material_cost_value_material_ean_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                ("end_date", models.DateField(verbose_name="Data de Fim")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="budget.material",
                    ),
                ),
            ],
        ),
    ]
