# Generated by Django 5.1.2 on 2024-10-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0029_materialprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="ean_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Código EAN"
            ),
        ),
    ]
