# Generated by Django 5.1.2 on 2024-10-22 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0030_alter_material_ean_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name": "Orçamento", "verbose_name_plural": "Orçamentos"},
        ),
        migrations.AlterModelOptions(
            name="budgetitem",
            options={
                "verbose_name": "Item do Orçamento",
                "verbose_name_plural": "Itens do Orçamento",
            },
        ),
        migrations.AlterModelOptions(
            name="price_list",
            options={
                "ordering": ["-start_date", "material__full_name"],
                "verbose_name": "Lista de Preços",
                "verbose_name_plural": "Listas de Preços",
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="tax_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor dos Impostos",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="value_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Total",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="tax_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor dos Impostos Unitário",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Unitário",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="value_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Total",
            ),
        ),
    ]
